name: Updating Packages

on: [workflow-dispatch]

jobs:
  watch:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Check outdated packages
      uses: dotnet packages --outdated
